/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aquresque;

import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class KirimBarangDialog extends javax.swing.JFrame {

    /**
     * Creates new form KirimBarangDialog
     */
    public KirimBarangDialog() {
        initComponents();
        
        String[] semuaProvinsi = {
        "Aceh", "Sumatera Utara", "Sumatera Barat", "Riau", "Kepulauan Riau", "Jambi", "Bengkulu",
        "Sumatera Selatan", "Kepulauan Bangka Belitung", "Lampung", "Banten", "DKI Jakarta",
        "Jawa Barat", "Jawa Tengah", "Daerah Istimewa Yogyakarta", "Jawa Timur", "Bali",
        "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Kalimantan Barat", "Kalimantan Tengah",
        "Kalimantan Selatan", "Kalimantan Timur", "Kalimantan Utara", "Sulawesi Utara", "Gorontalo",
        "Sulawesi Tengah", "Sulawesi Barat", "Sulawesi Selatan", "Sulawesi Tenggara", "Maluku",
        "Maluku Utara", "Papua Barat", "Papua", "Papua Selatan", "Papua Tengah",
        "Papua Pegunungan", "Papua Barat Daya"
    };

    cbx_provinsi.setModel(new javax.swing.DefaultComboBoxModel<>(semuaProvinsi));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_kodeBrg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbx_provinsi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tf_kotaDistribusi = new javax.swing.JTextField();
        btn_kirimDistribusi = new javax.swing.JButton();
        btn_cancelDistribusi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("KIRIM BARANG");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("KODE BRG :");

        tf_kodeBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kodeBrgActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("TUJUAN (PROVINSI) : ");

        cbx_provinsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_provinsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_provinsiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("TUJUAN (KOTA) : ");

        tf_kotaDistribusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kotaDistribusiActionPerformed(evt);
            }
        });

        btn_kirimDistribusi.setBackground(new java.awt.Color(255, 152, 0));
        btn_kirimDistribusi.setText("SIMPAN");
        btn_kirimDistribusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimDistribusiActionPerformed(evt);
            }
        });

        btn_cancelDistribusi.setBackground(new java.awt.Color(255, 152, 0));
        btn_cancelDistribusi.setText("CANCEL");
        btn_cancelDistribusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelDistribusiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_kotaDistribusi))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_kodeBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_provinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(btn_cancelDistribusi)
                .addGap(37, 37, 37)
                .addComponent(btn_kirimDistribusi)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_kodeBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbx_provinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_kotaDistribusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kirimDistribusi)
                    .addComponent(btn_cancelDistribusi))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_kodeBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kodeBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kodeBrgActionPerformed

    private void tf_kotaDistribusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kotaDistribusiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kotaDistribusiActionPerformed

    private void btn_kirimDistribusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimDistribusiActionPerformed
        // TODO add your handling code here:
        String kode = tf_kodeBrg.getText();
        String provinsi = cbx_provinsi.getSelectedItem().toString();
        String kota = tf_kotaDistribusi.getText();

        if (kode.isEmpty() || kota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kode Barang dan Kota Tujuan harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Anda yakin ingin mengirim barang '" + kode + "'?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            // 1. Ambil detail barangnya dulu
            Barang detailBarang = DatabaseController.getDetailBarangByKode(kode);
            if (detailBarang == null) {
                JOptionPane.showMessageDialog(this, "Barang dengan kode " + kode + " tidak ditemukan.");
                return;
            }

            // 2. Kirim barangnya (ubah status)
            boolean kirimSukses = DatabaseController.kirimBantuan(kode);
            if (kirimSukses) {
                // 3. Jika kirim berhasil, CATAT riwayatnya
                boolean catatSukses = DatabaseController.catatRiwayatKirim(
                    detailBarang.getKode(),
                    detailBarang.getNama(),
                    detailBarang.getJumlah(),
                    detailBarang.getSatuan(),
                    provinsi,
                    kota
                );

                if (catatSukses) {
                    JOptionPane.showMessageDialog(this, "Barang berhasil dikirim dan riwayat dicatat!");
                    this.dispose();
                } else {
                     JOptionPane.showMessageDialog(this, "Status barang diubah, tapi GAGAL mencatat riwayat.");
                }
            }
        }
    }//GEN-LAST:event_btn_kirimDistribusiActionPerformed

    private void btn_cancelDistribusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelDistribusiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelDistribusiActionPerformed

    private void cbx_provinsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_provinsiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbx_provinsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KirimBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KirimBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KirimBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KirimBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KirimBarangDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelDistribusi;
    private javax.swing.JButton btn_kirimDistribusi;
    private javax.swing.JComboBox<String> cbx_provinsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tf_kodeBrg;
    private javax.swing.JTextField tf_kotaDistribusi;
    // End of variables declaration//GEN-END:variables
}
