/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aquresque;

import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class LaporanFrame extends javax.swing.JFrame {

    /**
     * Creates new form LaporanFrame
     */
    public LaporanFrame() {
        initComponents();
        loadLaporanData();
    }

    private void loadLaporanData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Kode Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah");
        model.addColumn("Satuan");
        model.addColumn("Status");

        try {
            ResultSet rs = DatabaseController.getAllBantuan();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("kode_brg"),
                    rs.getString("jenis_brg"),
                    rs.getString("nama_brg"),
                    rs.getInt("jumlah"),
                    rs.getString("satuan"),
                    rs.getString("status")
                });
            }
            tbl_laporanFrame.setModel(model);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data laporan: " + e.getMessage());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_userLaporan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_laporanFrame = new javax.swing.JTable();
        btn_refreshLaporan = new javax.swing.JButton();
        btn_mainPage = new javax.swing.JButton();
        tf_cariBrgLaporan = new javax.swing.JTextField();
        btn_cariBrg = new javax.swing.JButton();
        btn_riwayatBrg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aquresque/aquresquelogo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Hai,");

        lbl_userLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_userLaporan.setText("User");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Berikut tentang Laporan");

        tbl_laporanFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_laporanFrame);

        btn_refreshLaporan.setBackground(new java.awt.Color(204, 255, 0));
        btn_refreshLaporan.setText("REFRESH DATA");
        btn_refreshLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshLaporanActionPerformed(evt);
            }
        });

        btn_mainPage.setBackground(new java.awt.Color(204, 255, 0));
        btn_mainPage.setText("MAIN PAGE");
        btn_mainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainPageActionPerformed(evt);
            }
        });

        tf_cariBrgLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cariBrgLaporanActionPerformed(evt);
            }
        });

        btn_cariBrg.setBackground(new java.awt.Color(51, 51, 0));
        btn_cariBrg.setText("CARI");
        btn_cariBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariBrgActionPerformed(evt);
            }
        });

        btn_riwayatBrg.setBackground(new java.awt.Color(204, 255, 0));
        btn_riwayatBrg.setText("RIWAYAT BARANG");
        btn_riwayatBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_riwayatBrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_userLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(646, 646, 646))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_cariBrgLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cariBrg))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_riwayatBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_refreshLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_userLaporan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btn_refreshLaporan)
                    .addComponent(btn_mainPage)
                    .addComponent(btn_riwayatBrg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cariBrgLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cariBrg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshLaporanActionPerformed
        // TODO add your handling code here:
        loadLaporanData();
        JOptionPane.showMessageDialog(this, "Laporan telah diperbarui.");
    }//GEN-LAST:event_btn_refreshLaporanActionPerformed

    private void btn_mainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainPageActionPerformed
        // TODO add your handling code here:
        MainFrame mainHome = new MainFrame();
        mainHome.setVisible(true);
    }//GEN-LAST:event_btn_mainPageActionPerformed

    private void tf_cariBrgLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cariBrgLaporanActionPerformed
        // TODO add your handling code here:
        btn_cariBrg.doClick();
    }//GEN-LAST:event_tf_cariBrgLaporanActionPerformed

    private void btn_cariBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariBrgActionPerformed
        // TODO add your handling code here:
        String keyword = tf_cariBrgLaporan.getText();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Kode Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah");
        model.addColumn("Satuan");
        model.addColumn("Status");

        try {
            ResultSet rs = DatabaseController.searchBarang(keyword);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("kode_brg"),
                    rs.getString("jenis_brg"),
                    rs.getString("nama_brg"),
                    rs.getInt("jumlah"),
                    rs.getString("satuan"),
                    rs.getString("status")
                });
            }

            tbl_laporanFrame.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan hasil pencarian: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_cariBrgActionPerformed

    private void btn_riwayatBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_riwayatBrgActionPerformed
        // TODO add your handling code here:
        RiwayatBarangDialog riwDialog = new RiwayatBarangDialog();
        riwDialog.setVisible(true);
    }//GEN-LAST:event_btn_riwayatBrgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cariBrg;
    private javax.swing.JButton btn_mainPage;
    private javax.swing.JButton btn_refreshLaporan;
    private javax.swing.JButton btn_riwayatBrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_userLaporan;
    private javax.swing.JTable tbl_laporanFrame;
    private javax.swing.JTextField tf_cariBrgLaporan;
    // End of variables declaration//GEN-END:variables
}
