/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aquresque;

import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class RiwayatBarangDialog extends javax.swing.JFrame {

    /**
     * Creates new form RiwayatBarangDialog
     */
    public RiwayatBarangDialog() {
        initComponents();
        loadRiwayatData();
    }

    private void loadRiwayatData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("KODE BRG");
        model.addColumn("NAMA BRG");
        model.addColumn("JUMLAH");
        model.addColumn("SATUAN");
        model.addColumn("PROVINSI");
        model.addColumn("KOTA");
        model.addColumn("TGL KIRIM");

        try {
            ResultSet rs = DatabaseController.getSemuaRiwayat();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_brg"),
                    rs.getString("nama_brg"),
                    rs.getInt("jumlah"),
                    rs.getString("satuan"),
                    rs.getString("provinsi_tujuan"),
                    rs.getString("kota_tujuan"),
                    rs.getTimestamp("tanggal_kirim")
                });
            }
            tbl_riwayatDistribusi.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat riwayat: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_riwayatDistribusi = new javax.swing.JTable();
        btn_kembaliKirim = new javax.swing.JButton();
        btn_refreshBrgDistribusi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("RIWAYAT PENGIRIMAN BARANG");

        tbl_riwayatDistribusi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_riwayatDistribusi);

        btn_kembaliKirim.setBackground(new java.awt.Color(255, 152, 0));
        btn_kembaliKirim.setText("KEMBALI");
        btn_kembaliKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliKirimActionPerformed(evt);
            }
        });

        btn_refreshBrgDistribusi.setBackground(new java.awt.Color(255, 152, 0));
        btn_refreshBrgDistribusi.setText("REFRESH BARANG");
        btn_refreshBrgDistribusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshBrgDistribusiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(193, 193, 193))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_refreshBrgDistribusi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kembaliKirim)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_refreshBrgDistribusi)
                    .addComponent(btn_kembaliKirim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliKirimActionPerformed
        // TODO add your handling code here:
        DistribusiFrame disFrame = new DistribusiFrame();
        disFrame.setVisible(true);
    }//GEN-LAST:event_btn_kembaliKirimActionPerformed

    private void btn_refreshBrgDistribusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshBrgDistribusiActionPerformed
        // TODO add your handling code here:
        loadRiwayatData();
        JOptionPane.showMessageDialog(this, "Tabel distribusi telah diperbarui.");
    }//GEN-LAST:event_btn_refreshBrgDistribusiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatBarangDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembaliKirim;
    private javax.swing.JButton btn_refreshBrgDistribusi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_riwayatDistribusi;
    // End of variables declaration//GEN-END:variables
}
